"""Companion paper (paper/companion/observational.tex): the summary table of the simulated-industry Monte Carlo.

Reads output/tables/m6_montecarlo_industry_summary.csv (module m6_montecarlo, v2 run; no estimation is redone here)
and writes paper/companion/tables/industry_mc.tex: bias [RMSE] of the frontier elasticity gamma and of TFP growth per
generation for four estimators under four compute rules and a flagship-only sample.

Usage: .venv/bin/python code/paper/make_companion_tables.py
"""
import os

import pandas as pd

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
SRC = os.path.join(ROOT, "output", "tables", "m6_montecarlo_industry_summary.csv")
OUT = os.path.join(ROOT, "paper", "companion", "tables", "industry_mc.tex")

SCEN = [("exog", "(a)"), ("funding", "(b)"), ("target", "(c)"), ("predet", "(d)"), ("funding_flag", "(e)")]
EST = [
    ("E1_pooled_huber", "Pooled Huber, $E$ free"),
    ("E2_pooled_nls", "Pooled NLS, generation effects"),
    ("E3_lab_fe", "Developer effects"),
    ("E5_labgen_fe", "Developer $\\times$ generation effects"),
]
PANELS = [("gamma", "Panel A. Frontier elasticity $\\gamma$ (truth 0.178)"),
          ("tfp_growth", "Panel B. Productivity growth per generation (truth 0.150)")]


def fmt(x):
    s = f"{x:.3f}"
    if s == "-0.000":
        s = "0.000"
    return s.replace("-", "$-$") if s.startswith("-") else s


def main():
    d = pd.read_csv(SRC)
    lines = [
        "% Generated by code/paper/make_companion_tables.py from output/tables/m6_montecarlo_industry_summary.csv.",
        "\\begin{table}[tp]",
        "\\centering",
        "\\caption{Production-Function Estimators in a Simulated Industry}",
        "\\label{tab:industry}",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{5pt}",
        "\\begin{tabular}{@{}l ccccc@{}}",
        "\\toprule",
        " & \\multicolumn{4}{c}{All released models} & Flagships only \\\\",
        "\\cmidrule(lr){2-5}\\cmidrule(lr){6-6}",
        " & (a) & (b) & (c) & (d) & (e) \\\\",
        "Compute rule: & Exogenous & Funding & Target & Predetermined & Funding \\\\",
        "\\midrule",
    ]
    for k, (param, title) in enumerate(PANELS):
        if k:
            lines.append("\\addlinespace[3pt]")
        lines.append(f"\\multicolumn{{6}}{{@{{}}l}}{{\\textit{{{title}}}}} \\\\")
        for est, lab in EST:
            cells, rm = [], []
            for sc, _ in SCEN:
                r = d[(d.scenario == sc) & (d.estimator == est) & (d.param == param)]
                if r.empty or pd.isna(r.bias.iloc[0]):
                    cells.append("n.a.")
                    rm.append("")
                else:
                    cells.append(fmt(r.bias.iloc[0]))
                    rm.append(f"[{r.rmse.iloc[0]:.3f}]")
            lines.append(lab + " & " + " & ".join(cells) + " \\\\")
            lines.append(" & " + " & ".join(rm) + " \\\\")
    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        "\\par\\smallskip",
        "\\begin{tablenotes}Bias [root-mean-squared error] over 400 replications per column. Forty developers each "
        "produce six generations of models and release one to four models per generation, about eightfold apart in "
        "compute; productivity is Hicks-neutral, $\\omega_{ft}=0.15(t-1)+x_{ft}$ with $x_{ft}$ a persistent AR(1) "
        "(coefficient 0.8, standard deviation 0.25). Compute rules: (a) exogenous budgets; (b) funding, log compute rises "
        "by $2x_{ft}$; (c) a common loss target reached by buying compute; (d) predetermined budgets, log compute rises "
        "by $2x_{f,t-1}$; (e) rule (b) with one model per developer and generation. Allocations include inference "
        "demand (mean log wedge 0.46) and allocation errors (standard deviation 0.2 in $\\ln(D/N)$). The pooled Huber "
        "fit estimates $E$ and has no time effects, as is common in machine-learning practice; the other estimators "
        "know $E$. Developer $\\times$ generation fixed effects use only the menu of sizes within a developer's "
        "generation and are not defined with flagships only (n.a.). Productivity growth: mean change in generation "
        "means of $y-\\hat F(n,d)$. Every estimator starts from data-based values. The calibration is illustrative; "
        "magnitudes scale with the assumed share of productivity-driven variation in compute. Appendix "
        "Table~\\ref{tab:industry-full} reports all estimators and parameters.\\end{tablenotes}",
        "\\begin{tablenotes}[Source]Author's simulations; replication code \\texttt{code/analysis/m6\\_montecarlo} "
        "(entry point \\texttt{run\\_v2.py}).\\end{tablenotes}",
        "\\end{table}",
    ]
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
