"""LaLonde-style comparison: observational estimators vs the experimental benchmark on the same output.

Benchmark ("truth") construction.  Benchmark logits are concave in (ln N, ln D) over the experimental range
(curvature F-tests in experiments.curvature_check): the D-elasticity falls and the N-elasticity rises with tokens per
parameter.  A single global slope is therefore not a well-defined target, and observational models (median D/N ~200)
sit in a different part of the technology than Chinchilla-style sweeps.  Two comparisons are produced:
  (1) run()/make_table(): all estimators (incl. FD, ACF-style, IV, EIV, reverse regression) on the overlap and full
      observational samples, next to the GLOBAL log-linear experimental fits (Table 6b; not design-matched);
  (2) design_matched()/make_matched_table(): the headline LaLonde test (Table 6).  Each estimator is applied, on the
      same observational models (restricted to the convex hull of the experimental (ln N, ln D) points), both to the
      observed outputs and to counterfactual outputs generated by the experimental technology (a quadratic surface
      fitted to the designed sweeps).  bias = difference; benchmark SEs from bootstrap refits of the surface.
"""
from __future__ import annotations

import os

import numpy as np
import pandas as pd
import statsmodels.api as sm

import observational as ob
from common import PREFIX, TABDIR, fmt, ols, write_tex_table

EST_ORDER = ["OLS", "Year FE", "Developer FE", "Family FE", "Mundlak", "Lab x period FE", "FD across generations",
             "ACF-style (AR(1) omega, gens)", "IV: frontier FLOP/$", "IV: own-hardware FLOP/$",
             "OLS, EIV-corrected (empirical)", "Family FE, EIV-corrected (empirical)",
             "Family FE, EIV-corrected (Epoch 'Confident')", "Notable only", "OP-style selection control",
             "Reverse (c on y)", "Reverse (c on y), family FE"]


def local_benchmark(lad, n0, d0, out, targets=True):
    d = lad if targets else lad[~lad.target]
    d = d.dropna(subset=[out]).copy()
    x, z = d.n - n0, d.d - d0
    X = pd.DataFrame({"n": x, "d": z, "n2": x ** 2, "d2": z ** 2, "nd": x * z})
    r = ols(d[out], sm.add_constant(X))
    b = r.params[["n", "d"]].values
    V = r.cov_params().loc[["n", "d"], ["n", "d"]].values
    return dict(theta_N=b[0], se_N=np.sqrt(V[0, 0]), theta_D=b[1], se_D=np.sqrt(V[1, 1]),
                ray=0.5 * (b[0] + b[1]), se_ray=0.5 * np.sqrt(V[0, 0] + V[1, 1] + 2 * V[0, 1]), V=V, n_obs=len(d))


def design_projection(d, fe=None):
    """b_n, b_d: projections of n and d on c (after within-`fe` demeaning)."""
    x = d[["n", "d", "c"]].copy()
    if fe is not None:
        x = x - d.groupby(fe)[["n", "d", "c"]].transform("mean")
    vc = x.c.var()
    return x.n.cov(x.c) / vc, x.d.cov(x.c) / vc


def run(df, lad, gad, dd_fin, exp_est, out="y_hellaswag", sample="overlap", B_acf=300, seed=0):
    mask = df[sample] if sample in df else df.main
    d = df[mask].dropna(subset=[out, "n", "d"]).copy()
    n0, d0 = d.n.mean(), d.d.mean()
    bench = local_benchmark(lad, n0, d0, out)
    # observational estimators
    res, dd = ob.run_estimators(df, out, sample, mask)
    rows = []
    # dynamic estimators on the generation panel (uses all main-sample generations of lines present)
    cell, pairs = ob.generation_panel(d, out)
    fd, p = ob.fd_gen(pairs)
    for par, nm in [("theta_N", "dn"), ("theta_D", "dd")]:
        rows.append(dict(estimator="FD across generations", param=par, est=fd.params[nm], se=fd.bse[nm], n_obs=len(p),
                         n_clusters=p.line.nunique()))
    rows.append(dict(estimator="FD across generations", param="theta_C_ray", est=0.5 * (fd.params.dn + fd.params.dd),
                     se=0.5 * np.sqrt(fd.cov_params().loc["dn", "dn"] + fd.cov_params().loc["dd", "dd"] + 2 * fd.cov_params().loc["dn", "dd"]),
                     n_obs=len(p), n_clusters=p.line.nunique()))
    acf, path = ob.acf_gen(pairs)
    bs = ob.acf_bootstrap(pairs, B=B_acf, seed=seed)
    for par in ["theta_N", "theta_D"]:
        lo, hi = np.nanpercentile(bs[par], [2.5, 97.5])
        rows.append(dict(estimator="ACF-style (AR(1) omega, gens)", param=par, est=acf[par], se=np.nanstd(bs[par], ddof=1),
                         lo=lo, hi=hi, n_obs=acf["n_pairs"], n_clusters=pairs.line.nunique(), rho=acf["rho"]))
    ray_bs = 0.5 * (bs.theta_N + bs.theta_D)
    rows.append(dict(estimator="ACF-style (AR(1) omega, gens)", param="theta_C_ray", est=0.5 * (acf["theta_N"] + acf["theta_D"]),
                     se=np.nanstd(ray_bs, ddof=1), lo=np.nanpercentile(ray_bs, 2.5), hi=np.nanpercentile(ray_bs, 97.5),
                     n_obs=acf["n_pairs"], n_clusters=pairs.line.nunique(), rho=acf["rho"]))
    n_triples = int(cell.dropna(subset=["y_l2"]).shape[0])
    # IV (compute-only)
    iv_rows = []
    for nm, z, ctl in [("IV: frontier FLOP/$", "z_frontier", None), ("IV: frontier FLOP/$ + developer FE", "z_frontier", "developer"),
                       ("IV: frontier FLOP/$ + developer FE + trend", "z_frontier", ["developer", "t"]),
                       ("IV: own-hardware FLOP/$", "z_own", None),
                       ("IV: China x post-export-control + dev FE + year FE", "china_post", ["developer", "year"])]:
        r = ob.iv_compute(d, out, z, controls=ctl)
        iv_rows.append(dict(estimator=nm, **r))
        rows.append(dict(estimator=nm, param="theta_C", est=r["est"], se=r["se"], n_obs=r["n_obs"],
                         n_clusters=r["n_clusters"], F=r["F"], ar_lo=r["ar_lo"], ar_hi=r["ar_hi"], ar_type=r["ar_type"]))
    # EIV
    x = d.dropna(subset=["C_epoch"])
    meth = x.C_method.fillna("")
    indep = x[meth.str.startswith("Hardware") | meth.str.startswith("Reported")]
    s_emp = float(np.log(indep.C_epoch / indep.C).std()) if len(indep) >= 5 else 0.25
    s_conf = np.log(3) / 1.645
    eiv = ob.eiv_correction(df, out, mask, {"empirical": s_emp, "Epoch 'Confident'": s_conf})
    for _, r in eiv.iterrows():
        rows.append(dict(estimator=r.estimator, param="theta_C", est=r.est, se=r.se, n_obs=r.n_obs, reliability=r.reliability))
    allr = pd.concat([res.drop(columns=["output", "sample"]), pd.DataFrame(rows)], ignore_index=True)
    allr["output"], allr["sample"] = out, sample
    # truths
    bn_pool, bd_pool = design_projection(d)
    bn_fam, bd_fam = design_projection(d, "family")
    tr = dict(theta_N=bench["theta_N"], theta_D=bench["theta_D"], theta_C_ray=bench["ray"],
              theta_C_pooled=bench["theta_N"] * bn_pool + bench["theta_D"] * bd_pool,
              theta_C_within=bench["theta_N"] * bn_fam + bench["theta_D"] * bd_fam,
              se_N=bench["se_N"], se_D=bench["se_D"], se_ray=bench["se_ray"],
              b_n_pool=bn_pool, b_d_pool=bd_pool, b_n_fam=bn_fam, b_d_fam=bd_fam, n0=n0, d0=d0,
              N0=np.exp(n0), D0=np.exp(d0), n_triples=n_triples, sigma_u_emp=s_emp, n_indep_C=len(indep))
    V = bench["V"]
    for k, (bn, bdd) in {"pooled": (bn_pool, bd_pool), "within": (bn_fam, bd_fam)}.items():
        w = np.array([bn, bdd])
        tr[f"se_C_{k}"] = float(np.sqrt(w @ V @ w))
    return allr, tr, pd.DataFrame(iv_rows), path


def _truth_for(estimator, param, tr):
    if param in ("theta_N", "theta_D", "theta_C_ray"):
        return tr[param]
    within = any(k in estimator for k in ["Family FE", "Mundlak", "Developer FE", "Lab x period", "family FE"])
    return tr["theta_C_within"] if within else tr["theta_C_pooled"]


def make_table(allr, tr, exp_est, out, sample, label_out, fname):
    """Table 6: rows = estimators; columns = theta_N, theta_D, theta_C (ray) from the (n,d) spec, and theta_C from the
    compute-only spec, each with SE in parentheses; last column: N obs / clusters."""
    def cell(e, par, spec):
        r = allr[(allr.estimator == e) & (allr.param == par)]
        if spec is not None and "spec" in r:
            r2 = r[r.spec == spec]
            r = r2 if len(r2) else r[r.spec.isna()]
        if not len(r):
            return None
        return r.iloc[0]

    rows_csv, rows_tex = [], []
    # Panel A: experimental
    rows_tex.append(["#Panel A. Experimental benchmarks (designed sweeps)"])
    ex = exp_est[exp_est.output == out]
    for ds in ["OLMo ladder", "OLMo ladder + OLMo-2", "Gadre et al. (N>=0.1B)", "DataDecide"]:
        e = ex[ex.dataset == ds]
        if not len(e):
            continue
        g = lambda p: e[e.param == p].iloc[0] if (e.param == p).any() else None
        vals = [g("theta_N"), g("theta_D"), g("theta_C_ray")]
        nobs = int(e.n_obs.iloc[0])
        top = [ds.replace(">=", "$\\geq$")] + [fmt(v.est) if v is not None else "" for v in vals] + ["", str(nobs)]
        bot = [""] + [f"({fmt(v.se)})" if v is not None else "" for v in vals] + ["", ""]
        rows_tex += [top, bot]
        rows_csv.append(dict(panel="A", row=ds, **{p: (v.est if v is not None else np.nan) for p, v in zip(["theta_N", "theta_D", "theta_C_ray"], vals)},
                             **{"se_" + p: (v.se if v is not None else np.nan) for p, v in zip(["theta_N", "theta_D", "theta_C_ray"], vals)}, n_obs=nobs))
    rows_tex.append(["\\midrule"])
    rows_tex.append([f"#Panel B. Observational estimators ({'overlap sample' if sample == 'overlap' else 'all dense base models'})"])
    for e in EST_ORDER:
        if e.startswith("IV") or "EIV" in e or e.startswith("Reverse") or e == "Notable only":
            vals = [None, None, None]
            c = cell(e, "theta_C", "c only") if not e.startswith("IV") and "EIV" not in e else cell(e, "theta_C", None)
        else:
            vals = [cell(e, "theta_N", "n,d"), cell(e, "theta_D", "n,d"), cell(e, "theta_C_ray", "n,d")]
            c = cell(e, "theta_C", "c only")
        if all(v is None for v in vals) and c is None:
            continue
        nobs = next((v for v in vals + [c] if v is not None)).n_obs
        ncl = next((v for v in vals + [c] if v is not None)).get("n_clusters", np.nan)
        def se_str(v):
            if v is None:
                return ""
            if "lo" in v and pd.notna(v.get("lo", np.nan)):
                return f"[{fmt(v.lo, 2)}, {fmt(v.hi, 2)}]"
            return f"({fmt(v.se)})"
        name = e
        if e.startswith("IV") and c is not None:
            name = f"{e} (F={c.F:.1f})"
        top = [name.replace("x period", "$\\times$ period").replace("$", "\\$") if "FLOP/$" in name else name.replace("x period", "$\\times$ period")] + \
              [fmt(v.est) if v is not None else "" for v in vals] + [fmt(c.est) if c is not None else "",
                                                                    f"{int(nobs)}" + (f"/{int(ncl)}" if pd.notna(ncl) else "")]
        bot = [""] + [se_str(v) for v in vals] + [se_str(c) if c is not None else "", ""]
        if e.startswith("IV") and c is not None and isinstance(c.get("ar_type"), str):
            ar = f"AR: {c.ar_type}" if c.ar_type != "interval" else f"AR [{fmt(c.ar_lo, 2)}, {fmt(c.ar_hi, 2)}]"
            bot[4] = bot[4] + " " + ar
        rows_tex += [top, bot]
        rows_csv.append(dict(panel="B", row=e, **{p: (v.est if v is not None else np.nan) for p, v in zip(["theta_N", "theta_D", "theta_C_ray"], vals)},
                             theta_C=c.est if c is not None else np.nan,
                             **{"se_" + p: (v.se if v is not None else np.nan) for p, v in zip(["theta_N", "theta_D", "theta_C_ray"], vals)},
                             se_theta_C=c.se if c is not None else np.nan, n_obs=nobs, n_clusters=ncl,
                             truth_theta_C=_truth_for(e, "theta_C", tr)))
    csv = pd.DataFrame(rows_csv)
    csv.to_csv(os.path.join(TABDIR, f"{PREFIX}_{fname}.csv"), index=False)
    header = ["", "$\\theta_N$", "$\\theta_D$", "$\\theta_C$ (ray)", "$\\theta_C$ (C only)", "Obs./clusters"]
    notes = (f"Output: {label_out}, i.e.\\ $\\text{{logit}}((acc-\\text{{chance}})/(1-\\text{{chance}}))$. "
             "$\\theta_N,\\theta_D$: coefficients on $\\ln N$ (total parameters) and $\\ln D$ (training tokens); "
             "$\\theta_C$ (ray) $=(\\theta_N+\\theta_D)/2$, the elasticity with respect to $\\ln C$ along a proportional "
             "($D\\propto N$) expansion; $\\theta_C$ (C only): slope on $\\ln C=\\ln 6ND$ in a compute-only regression. "
             "Panel A: designed sweeps (OLMo ladder: 5 sizes $\\times$ 5 token multipliers; OLMo-2 7B/13B targets; "
             "Gadre et al.: 3 corpora, corpus fixed effects; DataDecide: 25 recipes on the $D=100N$ ray, recipe fixed "
             "effects, clustered by recipe). HC1 standard errors in parentheses. These are GLOBAL log-linear fits over each "
             "design and are not matched to the observational design (see the design-matched Table 6). "
             "Panel B: standard errors clustered by developer in parentheses; bootstrap 95\\% intervals (clustered by "
             "product line) in brackets for the ACF-style estimator. FD and ACF-style use consecutive generations "
             "within (product line, size tier); Arellano--Bond requires three generations and has only "
             f"{tr['n_triples']} such cells, so it is not reported. IV: $\\ln C$ instrumented with the log FLOP/s per "
             "dollar of the best data-centre accelerator released six months before the model, or of the model's own "
             "training hardware (Epoch); F is the cluster-robust first-stage F; AR = Anderson--Rubin 95\\% set. EIV: "
             f"classical-error correction with $\\sigma_u={tr['sigma_u_emp']:.2f}$ (dispersion of independent Epoch compute "
             "estimates around $6ND$) or $\\ln 3/1.645$ (Epoch `Confident' class). Reverse: $1/b$ from regressing "
             "$\\ln C$ on the output (Nerlove).")
    write_tex_table(os.path.join(TABDIR, f"{PREFIX}_{fname}.tex"), header, rows_tex,
                    caption=f"Cross-lab production functions: observational estimators vs experimental benchmark ({label_out})",
                    label=f"tab:{fname}", notes=notes, colspec="lccccc", size="\\scriptsize")
    return csv


# ============================================================================= design-matched LaLonde comparison
# For every observational estimator we ask: what would the SAME estimator return on the SAME observational design
# if outputs were generated by the experimental technology (no lab TFP, no selection)?  y*_i = f_exp(n_i, d_i),
# f_exp = quadratic (translog-in-odds) surface fitted to designed sweeps; evaluated only inside the convex hull of
# the experimental (ln N, ln D) points (common-support trimming, Dehejia-Wahba style).  bias = est(y) - est(y*).
MATCH_EST = ["OLS", "Year FE", "Developer FE", "Family FE", "Lab x period FE", "OP-style selection control"]
MATCH_C_ONLY = ["IV: frontier FLOP/$", "IV: frontier FLOP/$ + developer FE", "IV: own-hardware FLOP/$",
                "OLS, EIV-corrected (Epoch 'Confident')", "Family FE, EIV-corrected (Epoch 'Confident')",
                "Reverse (c on y)", "Reverse (c on y), family FE"]
SIGMA_CONF = np.log(3) / 1.645   # Epoch 'Confident' class: 90% CI within a factor of 3


def exp_surface_data(lad, gad, which="ladder+gadre"):
    a = lad.assign(ds="ladder")
    if which == "ladder":
        return a
    b = gad[gad.N >= 1e8].assign(ds="gadre_" + gad.corpus)
    return pd.concat([a, b], ignore_index=True)


def fit_surface(E, out, center):
    n0, d0 = center
    x, z = E.n - n0, E.d - d0
    X = pd.DataFrame({"n": x, "d": z, "n2": x ** 2, "d2": z ** 2, "nd": x * z}, index=E.index)
    if E.ds.nunique() > 1:
        X = pd.concat([X, pd.get_dummies(E.ds, drop_first=True, dtype=float)], axis=1)
    r = sm.OLS(E[out], sm.add_constant(X)).fit(cov_type="HC1")
    return r


def predict_surface(r, n, d, center):
    n0, d0 = center
    x, z = n - n0, d - d0
    p = r.params
    return p["n"] * x + p["d"] * z + p["n2"] * x ** 2 + p["d2"] * z ** 2 + p["nd"] * x * z


def in_hull(E, pts):
    from scipy.spatial import Delaunay
    return Delaunay(E[["n", "d"]].values).find_simplex(pts) >= 0


def _estimates(d, yname):
    """Returns dict estimator -> dict(theta_N, theta_D, theta_C) (+ SEs) for outcome column yname."""
    out = {}
    d = d.copy()
    d["devyear"] = d.developer + "_" + d.year.astype(str)
    for est, fe in [("OLS", None), ("Year FE", "year"), ("Developer FE", "developer"), ("Family FE", "family"),
                    ("Lab x period FE", "devyear")]:
        r1 = ob._fit(d, yname, ["n", "d"], fe=fe)
        r2 = ob._fit(d, yname, ["c"], fe=fe)
        out[est] = dict(theta_N=r1.params["n"], theta_D=r1.params["d"], theta_C=r2.params["c"],
                        se_N=r1.bse["n"], se_D=r1.bse["d"], se_C=r2.bse["c"])
    # compute-only estimators (theta_C): IV, EIV-corrected, reverse regression
    from linearmodels.iv import IV2SLS
    for nm, z, fe in [("IV: frontier FLOP/$", "z_frontier", None), ("IV: frontier FLOP/$ + developer FE", "z_frontier", "developer"),
                      ("IV: own-hardware FLOP/$", "z_own", None)]:
        dz = d.dropna(subset=[z])
        if len(dz) < 12:
            continue
        Cx = sm.add_constant(ob._dummies(dz, fe) if fe else pd.DataFrame(index=dz.index), has_constant="add")
        try:
            m = IV2SLS(dz[yname], Cx, dz[["c"]], dz[[z]]).fit(cov_type="clustered", clusters=pd.factorize(dz.developer)[0])
            fs = ob.ols(dz.c, pd.concat([Cx, dz[[z]]], axis=1), cluster=dz.developer)
            out[nm] = dict(theta_C=float(m.params["c"]), se_C=float(m.std_errors["c"]), F=float(fs.tvalues[z] ** 2), n=len(dz))
        except Exception:
            pass
    for nm, fe in [("OLS, EIV-corrected (Epoch 'Confident')", None), ("Family FE, EIV-corrected (Epoch 'Confident')", "family")]:
        r = ob._fit(d, yname, ["c"], fe=fe)
        cc = d.c if fe is None else d.c - d.groupby(fe).c.transform("mean")
        lam = 1 - SIGMA_CONF ** 2 / cc.var()
        # the counterfactual y* is built from the SAME (mismeasured) inputs, so it needs no correction
        k = 1.0 if yname == "ystar" else lam
        out[nm] = dict(theta_C=float(r.params["c"]) / k, se_C=float(r.bse["c"]) / k, reliability=lam)
    for nm, fe in [("Reverse (c on y)", None), ("Reverse (c on y), family FE", "family")]:
        r = ob._fit(d, "c", [yname], fe=fe)
        b = float(r.params[yname])
        out[nm] = dict(theta_C=1.0 / b, se_C=float(r.bse[yname]) / b ** 2)
    ps = d["ps"] if "ps" in d else None
    if ps is not None:
        r1 = ob._fit(d, yname, ["n", "d", "ps", "ps2"])
        r2 = ob._fit(d, yname, ["c", "ps", "ps2"])
        out["OP-style selection control"] = dict(theta_N=r1.params["n"], theta_D=r1.params["d"], theta_C=r2.params["c"],
                                                 se_N=r1.bse["n"], se_D=r1.bse["d"], se_C=r2.bse["c"])
    return out


def design_matched(df, lad, gad, out="y_hellaswag", surface="ladder+gadre", B=300, seed=0):
    import statsmodels.formula.api as smf
    E = exp_surface_data(lad, gad, surface).dropna(subset=[out])
    obs = df[df.main].dropna(subset=[out]).copy()
    obs = obs[in_hull(E, obs[["n", "d"]].values)].copy()
    center = (E.n.mean(), E.d.mean())
    r = fit_surface(E, out, center)
    obs["ystar"] = predict_surface(r, obs.n.values, obs.d.values, center)
    try:
        obs["notable_i"] = obs.notable.astype(int)
        pm = smf.logit("notable_i ~ n + d + t", data=obs).fit(disp=0)
        obs["ps"] = pm.predict(obs)
        obs["ps2"] = obs.ps ** 2
    except Exception:
        pass
    est_y = _estimates(obs, out)
    est_s = _estimates(obs, "ystar")
    rng = np.random.default_rng(seed)
    draws = {k: [] for k in est_s}
    groups = [g.index.values for _, g in E.groupby("ds")]
    for b in range(B):
        idx = np.concatenate([rng.choice(g, len(g), replace=True) for g in groups])
        Eb = E.loc[idx].reset_index(drop=True)
        try:
            rb = fit_surface(Eb, out, center)
        except Exception:
            continue
        ob_ = obs.copy()
        ob_["ystar"] = predict_surface(rb, obs.n.values, obs.d.values, center)
        eb = _estimates(ob_, "ystar")
        for k, v in eb.items():
            draws[k].append(v)
    rows = []
    for k in est_y:
        dr = pd.DataFrame(draws[k])
        for par, sek in [("theta_N", "se_N"), ("theta_D", "se_D"), ("theta_C", "se_C")]:
            if par not in est_y[k] or k not in est_s:
                continue
            bse = float(dr[par].std(ddof=1))
            bias = est_y[k][par] - est_s[k][par]
            rows.append(dict(estimator=k, output=out, surface=surface, param=par, obs=est_y[k][par], obs_se=est_y[k][sek],
                             bench=est_s[k][par], bench_se=bse, bench_lo=float(dr[par].quantile(0.025)),
                             bench_hi=float(dr[par].quantile(0.975)), bias=bias,
                             bias_se=float(np.sqrt(est_y[k][sek] ** 2 + bse ** 2)),
                             n_obs=est_y[k].get("n", len(obs)), F=est_y[k].get("F", np.nan),
                             reliability=est_y[k].get("reliability", np.nan),
                             n_families=obs.family.nunique(), n_dev=obs.developer.nunique()))
    info = dict(n_hull=len(obs), n_exp=len(E), surface_R2=r.rsquared, center_N=np.exp(center[0]), center_D=np.exp(center[1]),
                surface_params=r.params.to_dict(), B=B, B_ok=int(min(len(v) for v in draws.values())) if draws else 0)
    return pd.DataFrame(rows), obs, info


def make_matched_table(res, out_label, fname, info):
    rows_tex, csv = [], []
    for e in MATCH_EST:
        r = res[res.estimator == e].set_index("param")
        if not len(r):
            continue
        top, bot = [e.replace("x period", "$\\times$ period")], [""]
        for par in ["theta_N", "theta_D", "theta_C"]:
            x = r.loc[par]
            top += [fmt(x.obs), fmt(x.bench), fmt(x.bias)]
            bot += [f"({fmt(x.obs_se)})", f"({fmt(x.bench_se)})", f"({fmt(x.bias_se)})"]
        rows_tex += [top, bot]
    rows_tex.append(["\\midrule"])
    rows_tex.append(["#Compute-only estimators"])
    for e in MATCH_C_ONLY:
        r = res[(res.estimator == e) & (res.param == "theta_C")]
        if not len(r):
            continue
        x = r.iloc[0]
        name = e.replace("$", "\\$").replace("'Confident'", "`Confident'")
        if np.isfinite(x.F):
            name += f" (F={x.F:.1f}, n={int(x.n_obs)})"
        rows_tex += [[name, "", "", "", "", "", "", fmt(x.obs), fmt(x.bench), fmt(x.bias)],
                     ["", "", "", "", "", "", "", f"({fmt(x.obs_se)})", f"({fmt(x.bench_se)})", f"({fmt(x.bias_se)})"]]
    header = ["", "Obs.", "Exp.", "Bias", "Obs.", "Exp.", "Bias", "Obs.", "Exp.", "Bias"]
    pre = ("\\multicolumn{1}{c}{} & \\multicolumn{3}{c}{$\\theta_N$ ($\\ln N$)} & \\multicolumn{3}{c}{$\\theta_D$ ($\\ln D$)} & "
           "\\multicolumn{3}{c}{$\\theta_C$ ($\\ln C$ only)} \\\\ \\cmidrule(lr){2-4}\\cmidrule(lr){5-7}\\cmidrule(lr){8-10}")
    r0 = res.iloc[0]
    notes = (f"Output: {out_label}. Sample: the {int(r0.n_obs)} dense base models of the observational panel whose "
             f"$(\\ln N,\\ln D)$ lie inside the convex hull of the experimental runs ({int(r0.n_families)} families, "
             f"{int(r0.n_dev)} developers). Obs.: estimator applied to the observed benchmark logits (standard errors "
             "clustered by developer). Exp.: the same estimator applied, on the same models, to counterfactual outputs "
             "$y^*_i=\\hat f(\\ln N_i,\\ln D_i)$ generated by the experimental technology, a quadratic "
             "(translog-in-odds) surface fitted to the OLMo ladder + OLMo-2 targets and the Gadre et al. testbed "
             f"($N\\geq0.1$B; dataset intercepts), {info['n_exp']} runs, $R^2={info['surface_R2']:.3f}$; standard errors "
             f"from {info.get('B_ok', info.get('B'))} bootstrap refits of the surface (runs resampled within design). Bias = Obs. $-$ Exp.; its "
             "standard error treats the two as independent (they come from different data). With about 19 developer clusters, "
             "CR1 standard errors can overstate precision; restricted wild-cluster bootstrap p-values (Webb weights) for every "
             "bias are in the accompanying \\texttt{\\_wildboot.csv} file. The benchmark differs across estimators because each "
             "estimator weights the local elasticities of a non-log-linear technology differently. Compute-only rows: "
             "IV instruments $\\ln C$ with the log FLOP/s per dollar of the best data-centre accelerator released six "
             "months before the model (or of the model's own training hardware, Epoch); F = cluster-robust first-stage F. "
             "EIV: slope divided by the reliability ratio implied by Epoch's `Confident' class ($\\sigma_u=\\ln 3/1.645$); "
             "Reverse: $1/b$ from regressing $\\ln C$ on the output (Nerlove).")
    write_tex_table(os.path.join(TABDIR, f"{PREFIX}_{fname}.tex"), header, rows_tex,
                    caption=f"LaLonde test: observational estimators vs the experimental technology on the same design ({out_label})",
                    label=f"tab:{fname}", notes=notes, colspec="l" + "c" * 9, size="\\scriptsize")
    # add the spanner line after \toprule
    p = os.path.join(TABDIR, f"{PREFIX}_{fname}.tex")
    s = open(p).read().replace("\\toprule\n", "\\toprule\n" + pre + "\n", 1)
    open(p, "w").write(s)
    res.to_csv(os.path.join(TABDIR, f"{PREFIX}_{fname}.csv"), index=False)


# ============================================================================= [review addition] few-cluster inference
def _design(d, xs, fe):
    X = d[xs].astype(float).copy()
    if fe is not None:
        X = pd.concat([X, ob._dummies(d, fe)], axis=1)
    return sm.add_constant(X, has_constant="add")


def _cr1(X, u, g):
    """OLS coefficients' CR1 covariance (statsmodels' default small-sample correction)."""
    n, k = X.shape
    XtXi = np.linalg.pinv(X.T @ X)
    G = len(np.unique(g))
    meat = np.zeros((k, k))
    for c in np.unique(g):
        s = X[g == c].T @ u[g == c]
        meat += np.outer(s, s)
    return (G / (G - 1)) * ((n - 1) / (n - k)) * XtXi @ meat @ XtXi


def wild_cluster_test(d, yname, xs, fe, par, theta0, B=999, seed=0):
    """Restricted wild cluster bootstrap-t (Webb six-point weights; cameron2008bootstrap, webb2023reworking) of
    H0: coef[par] = theta0 with developer clusters. Used to check the few-cluster (G~19) CR1 inference on the
    Table 6 biases, treating the experimental benchmark as fixed (its bootstrap SE is small by comparison)."""
    rng = np.random.default_rng(seed)
    X = _design(d, xs, fe)
    cols = list(X.columns)
    j = cols.index(par)
    Xv, y = X.values, d[yname].values.astype(float)
    g = pd.factorize(d.developer)[0]
    b = np.linalg.lstsq(Xv, y, rcond=None)[0]
    u = y - Xv @ b
    t_obs = (b[j] - theta0) / np.sqrt(_cr1(Xv, u, g)[j, j])
    # restricted fit: impose coef[par] = theta0
    Xr = np.delete(Xv, j, axis=1)
    yr = y - theta0 * Xv[:, j]
    br = np.linalg.lstsq(Xr, yr, rcond=None)[0]
    fit_r, ur = Xr @ br + theta0 * Xv[:, j], yr - Xr @ br
    webb = np.array([-np.sqrt(1.5), -1.0, -np.sqrt(0.5), np.sqrt(0.5), 1.0, np.sqrt(1.5)])
    G = g.max() + 1
    ts = np.empty(B)
    for i in range(B):
        w = rng.choice(webb, G)[g]
        ys = fit_r + w * ur
        bs = np.linalg.lstsq(Xv, ys, rcond=None)[0]
        us = ys - Xv @ bs
        ts[i] = (bs[j] - theta0) / np.sqrt(_cr1(Xv, us, g)[j, j])
    return dict(t_cr1=float(t_obs), p_cr1_normal=float(2 * (1 - __import__("scipy").stats.norm.cdf(abs(t_obs)))),
                p_wild=float(np.mean(np.abs(ts) >= abs(t_obs))), n_clusters=int(G), B=B)


def wild_bias_table(res, hull_obs, out, fname, B=999, seed=0):
    """Wild-cluster p-values for H0: bias = 0 (obs estimator = experimental benchmark) for the Table 6 rows."""
    d = hull_obs.copy()
    d["devyear"] = d.developer + "_" + d.year.astype(str)
    rows = []
    for est, fe in [("OLS", None), ("Year FE", "year"), ("Developer FE", "developer"), ("Family FE", "family"),
                    ("Lab x period FE", "devyear")]:
        for par, xs, col in [("theta_N", ["n", "d"], "n"), ("theta_D", ["n", "d"], "d"), ("theta_C", ["c"], "c")]:
            r = res[(res.estimator == est) & (res.param == par)]
            if not len(r):
                continue
            th0 = float(r.bench.iloc[0])
            w = wild_cluster_test(d, out, xs, fe, col, th0, B=B, seed=seed)
            rows.append(dict(estimator=est, param=par, obs=float(r.obs.iloc[0]), bench=th0, bias=float(r.bias.iloc[0]),
                             bias_se=float(r.bias_se.iloc[0]), **w))
    W = pd.DataFrame(rows)
    W.to_csv(os.path.join(TABDIR, f"{PREFIX}_{fname}_wildboot.csv"), index=False)
    return W
